"""Update to lates

Revision ID: 47a7d8d4e5e7
Revises: 
Create Date: 2022-01-17 02:19:59.940054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a7d8d4e5e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen_at', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.drop_column('users', 'last_auth_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_auth_at', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'last_seen_at')
    # ### end Alembic commands ###
